### ISSUE TITLE
Cannot pip install portfoliolab on google colab

### ISSUE THREAD

**Issue by michaelmech** [hudson-and-thames/portfoliolab#4]
* portfoliolab
* Python version: `3.7`
* Operating System: `Windows`

I tried '!pip install portfoliolab' using google colabs but it returns:

"ERROR: Could not find a version that satisfies the requirement portfoliolab (from versions: none)
ERROR: No matching distribution found for portfoliolab"

It was working for me about 1 week ago, but maybe some  update changes have been made which result in this error.

**Comment by PanPip** [comment]
Hi @michaelmech!

Thank you for creating this report. 

This week we've moved PortfolioLab from PyPI to a private GitHub repository. To get the installation guide, get the package on https://portal.hudsonthames.org or contact the sales team via a form on https://hudsonthames.org.
